# Generated by Django 5.2.3 on 2025-06-21 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria (ex: Alimentação, Transporte)', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], default='despesa', help_text='Indica se é uma categoria de receita ou despesa.', max_length=10)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário proprietário da categoria. Deixe em branco para categorias globais.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('nome', 'usuario')},
            },
        ),
    ]
