# Generated by Django 5.2.3 on 2025-06-21 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(help_text='Nome da categoria (ex: Alimentação, Transporte)', max_length=100),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Breve descrição do gasto (ex: Supermercado, Almoço)', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do gasto (ex: 150.75)', max_digits=10)),
                ('data_gasto', models.DateField(help_text='Data em que o gasto ocorreu.')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('outros', 'Outros')], help_text='Forma de pagamento utilizada.', max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Notas adicionais sobre o gasto.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'despesa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='financas.categoria')),
                ('usuario', models.ForeignKey(help_text='Usuário que registrou este gasto.', on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-data_gasto', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Breve descrição da receita (ex: Salário, Freelance)', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da receita (ex: 1200.00)', max_digits=10)),
                ('data_receita', models.DateField(help_text='Data em que a receita foi recebida.')),
                ('observacoes', models.TextField(blank=True, help_text='Notas adicionais sobre a receita.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'receita'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='financas.categoria')),
                ('usuario', models.ForeignKey(help_text='Usuário que registrou esta receita.', on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_receita', '-criado_em'],
            },
        ),
    ]
